import fs from 'fs';
import path from 'path';

// 基于脚本自身位置解析路径（scripts/animation/ → 项目根目录），
// 避免依赖进程 cwd 导致移动脚本后路径失效。
const rootDir = path.resolve(import.meta.dirname, '../..');
const animDir = path.join(rootDir, 'src/ANIM');
const weaponsDir = path.join(rootDir, 'public/weapons');
const outputFile = path.join(rootDir, 'src/game/animation/AnimationData.ts');

if (!fs.existsSync(weaponsDir)) {
  fs.mkdirSync(weaponsDir, { recursive: true });
}

// ==================== 锚点矫正（手动） ====================
// 部分武器的 Lottie 锚点不在真实的旋转中心（剑柄/握持点）上，导致挥动时绕错点旋转。
// 这里按动画 key（baseKey）覆盖锚点，并同步补偿 positions 轨道，保证贴图视觉位置不变。
// key → { x, y }（新锚点，武器贴图像素坐标）
const ANCHOR_TWEAKS = {
  '112': { x: 30, y: 42 }, // 守卫者之剑：长剑，剑柄在贴图左端 ~30px（原锚点 51.69 在护手/剑身交界）
};

// 武器顺序矫正（手动）：
// 通用规则按"图层层级"排列武器（第一层=贴图-1，第三层=贴图-2），
// 个别动画的贴图命名与之不同（如帝国之盾 110 的贴图按 asset 序号命名），在此覆盖。
const WEAPON_ORDER_TWEAKS = {
  '110': ['asset_1', 'asset_2'], // 帝国之盾：贴图 110-1=asset_1(192x204)、110-2=asset_2(168x204)
};

// 图层缩放：100 表示无缩放（no-s / s=[100,100]）
function layerScale(layer) {
  const s = layer && layer.ks && layer.ks.s;
  if (!s) return 100;
  if (s.a === 0 && Array.isArray(s.k)) return s.k[0];
  if (s.a === 1 && Array.isArray(s.k) && s.k[0] && Array.isArray(s.k[0].s)) return s.k[0].s[0];
  return 100;
}

// 应用锚点矫正：改锚点 + 补偿 positions（asset px → comp px = *scale/100）
function applyAnchorTweak(weapon, tweak) {
  if (!weapon || !tweak) return;
  const dx = weapon.anchor.x - tweak.x;
  const dy = weapon.anchor.y - tweak.y;
  if (Math.abs(dx) < 0.01 && Math.abs(dy) < 0.01) return;
  const sx = (weapon.scale.x || 100) / 100;
  const sy = (weapon.scale.y || 100) / 100;
  weapon.anchor.x = tweak.x;
  weapon.anchor.y = tweak.y;
  for (const kf of weapon.tracks.positions) {
    kf.value.x = parseFloat((kf.value.x - dx * sx).toFixed(2));
    kf.value.y = parseFloat((kf.value.y - dy * sy).toFixed(2));
  }
  console.log(`  Anchor tweak: (${tweak.x}, ${tweak.y}), position compensated by (${parseFloat((-dx * sx).toFixed(2))}, ${parseFloat((-dy * sy).toFixed(2))})`);
}

// Read a Lottie property value (static a=0 or first keyframe of animated a=1)
function getValue(prop) {
  if (prop.a === 0 && Array.isArray(prop.k)) return prop.k[0];
  if (prop.a === 1 && Array.isArray(prop.k) && prop.k[0] && Array.isArray(prop.k[0].s)) return prop.k[0].s[0];
  return 100;
}

// 读取现有输出中已有的动画 key（增量模式用于跳过，避免覆盖用户对已有条目的微调）
function readExistingKeys() {
  const keys = new Set();
  if (!fs.existsSync(outputFile)) return keys;
  const content = fs.readFileSync(outputFile, 'utf8');
  const regex = /^  "([^"]+)": \{/gm;
  let m;
  while ((m = regex.exec(content)) !== null) keys.add(m[1]);
  return keys;
}

const header = `/**
 * This file is automatically generated by scripts/animation/parse_animations.js
 * DO NOT EDIT MANUALLY!
 */

export interface Keyframe<T> {
  t: number;
  value: T;
}

/** 单层（身体/武器）的变换关键帧轨道 */
export interface LayerTracks {
  positions: Keyframe<{ x: number; y: number }>[];
  rotations: Keyframe<number>[];
  /** 透明度关键帧（0~100，100=不透明），用于武器贴图切换/淡入淡出；无动画时为空数组 */
  opacities: Keyframe<number>[];
}

/** 武器层：贴图尺寸 + 缩放/锚点 + 变换轨道 */
export interface WeaponLayer {
  /** 武器贴图原始尺寸（像素），用于锚点归一化 */
  size: { x: number; y: number };
  /** 武器缩放（百分比，如 6 代表 6%） */
  scale: { x: number; y: number };
  /** 武器旋转中心锚点（贴图像素坐标） */
  anchor: { x: number; y: number };
  tracks: LayerTracks;
}

/**
 * 统一动画剪辑：一次动画 = 身体层 + 一到多个武器层（weapons 数组）。
 * 身体层描述贴图尺寸/锚点/图层缩放与身体变换；各武器层 positions 均为相对身体锚点的偏移（comp 像素，y 向下）。
 * 武器层数量 = 动画中武器个数（1 个主武器、2 个双武器、3 个双手武器…），贴图按 {dbId}-1.png / {dbId}-2.png / {dbId}-3.png 顺序对应。
 */
export interface AnimationClip {
  /** 动画总时长（帧，100fps） */
  duration: number;
  body: {
    /** 身体贴图原始尺寸（像素），用于把 comp 坐标换算到游戏本地坐标 */
    size: { x: number; y: number };
    /** 身体图层缩放（百分比，SVGator 层缩放；武器比例换算需除以它，如救星骑士 18%） */
    scale: { x: number; y: number };
    /** 身体层变换锚点（asset 像素坐标），也是身体旋转中心 */
    anchor: { x: number; y: number };
    tracks: LayerTracks;
  };
  /** 武器层数组（主武器 + 第二/三武器…），数量可变 */
  weapons: WeaponLayer[];
}

export const ANIMATIONS: Record<string, AnimationClip> = {
`;

// ==================== 提取逻辑 ====================

// 提取图层静态初值：p 为二维、r/s/a 为标量或二维
function extractLayerTracks(layer, bodyX, bodyY) {
  const ks = layer.ks || {};
  const positions = [];
  const rotations = [];
  const opacities = [];

  // Positions (p)：相对身体位置的偏移
  if (ks.p) {
    const wp = ks.p;
    if (wp.a === 0 && Array.isArray(wp.k)) {
      positions.push({ t: 0, value: { x: wp.k[0] - bodyX, y: wp.k[1] - bodyY } });
    } else if (wp.a === 1 && Array.isArray(wp.k)) {
      wp.k.forEach(kf => {
        if (kf.s && Array.isArray(kf.s)) {
          positions.push({
            t: Math.round(kf.t),
            value: { x: parseFloat((kf.s[0] - bodyX).toFixed(2)), y: parseFloat((kf.s[1] - bodyY).toFixed(2)) }
          });
        }
      });
    }
  }

  // Rotations (r)：标量
  if (ks.r) {
    const wr = ks.r;
    if (wr.a === 0) {
      const val = typeof wr.k === 'number' ? wr.k : (Array.isArray(wr.k) ? wr.k[0] : 0);
      rotations.push({ t: 0, value: parseFloat(val.toFixed(2)) });
    } else if (wr.a === 1 && Array.isArray(wr.k)) {
      wr.k.forEach(kf => {
        if (kf.s && Array.isArray(kf.s)) {
          rotations.push({
            t: Math.round(kf.t),
            value: parseFloat(kf.s[0].toFixed(2))
          });
        }
      });
    }
  }

  // Opacity (o)：0~100，用于武器贴图切换/淡入淡出
  if (ks.o) {
    const wo = ks.o;
    if (wo.a === 0) {
      const val = typeof wo.k === 'number' ? wo.k : (Array.isArray(wo.k) ? wo.k[0] : 100);
      opacities.push({ t: 0, value: parseFloat(val.toFixed(2)) });
    } else if (wo.a === 1 && Array.isArray(wo.k)) {
      wo.k.forEach(kf => {
        if (kf.s && Array.isArray(kf.s)) {
          opacities.push({
            t: Math.round(kf.t),
            value: parseFloat(kf.s[0].toFixed(2))
          });
        }
      });
    }
  }

  return { positions, rotations, opacities };
}

// ==================== 尾部静止帧裁剪 ====================
// 去掉关键帧末尾连续相同值的冗余帧（之后没有新动作的静止段），
// 并据此缩短动画 duration，避免攻击动画末尾拖着一段"定格"。
function trimTrackTail(frames, sameValue) {
  if (!frames || frames.length < 2) return frames;
  const out = frames.slice();
  while (out.length >= 2 && sameValue(out[out.length - 1], out[out.length - 2])) {
    out.pop();
  }
  return out;
}

function samePos(a, b) { return a.value.x === b.value.x && a.value.y === b.value.y; }
function sameNum(a, b) { return a.value === b.value; }

function trimTracks(tracks) {
  return {
    positions: trimTrackTail(tracks.positions, samePos),
    rotations: trimTrackTail(tracks.rotations, sameNum),
    opacities: trimTrackTail(tracks.opacities, sameNum),
  };
}

// 计算裁剪后动画时长：所有轨道最后一个关键帧时刻 + 1 帧（至少 1），与原时长取 min
function computeTrimmedDuration(duration, ...trackLists) {
  let lastT = 0;
  for (const list of trackLists) {
    if (list.length) lastT = Math.max(lastT, list[list.length - 1].t);
  }
  return Math.min(duration, Math.max(1, lastT + 1));
}

// 提取武器层（asset_1 / asset_2 …）
function extractWeapon(asset, layer, bodyX, bodyY) {
  const wks = layer.ks || {};

  // 锚点 (a)：旋转中心
  let anchorX = 0;
  let anchorY = 0;
  if (wks.a) {
    const wa = wks.a;
    if (wa.a === 0 && Array.isArray(wa.k)) {
      anchorX = wa.k[0];
      anchorY = wa.k[1];
    } else if (wa.a === 1 && Array.isArray(wa.k) && wa.k[0] && Array.isArray(wa.k[0].s)) {
      anchorX = wa.k[0].s[0];
      anchorY = wa.k[0].s[1];
    }
  }

  // 缩放 (s)：无缩放字段时默认 100（原尺寸）
  let scaleX = 100;
  let scaleY = 100;
  if (wks.s) {
    const ws = wks.s;
    if (ws.a === 0 && Array.isArray(ws.k)) {
      scaleX = ws.k[0];
      scaleY = ws.k[1];
    } else if (ws.a === 1 && Array.isArray(ws.k) && ws.k[0] && Array.isArray(ws.k[0].s)) {
      scaleX = ws.k[0].s[0];
      scaleY = ws.k[0].s[1];
    }
  }

  const tracks = extractLayerTracks(layer, bodyX, bodyY);

  return {
    base64: asset.p && asset.p.startsWith('data:image/png;base64,') ? asset.p.replace(/^data:image\/png;base64,/, "") : null,
    size: { x: asset.w || 0, y: asset.h || 0 },
    scale: { x: scaleX, y: scaleY },
    anchor: { x: anchorX, y: anchorY },
    tracks,
  };
}

// 渲染单个武器层代码（weapons 数组元素）
function renderWeapon(weapon) {
  return `      {
        size: { x: ${weapon.size.x}, y: ${weapon.size.y} },
        scale: { x: ${weapon.scale.x}, y: ${weapon.scale.y} },
        anchor: { x: ${weapon.anchor.x}, y: ${weapon.anchor.y} },
        tracks: {
          positions: ${JSON.stringify(weapon.tracks.positions)},
          rotations: ${JSON.stringify(weapon.tracks.rotations)},
          opacities: ${JSON.stringify(weapon.tracks.opacities)}
        }
      },
`;
}

// 处理单个动画文件：导出武器贴图并返回该动画的 TS 条目代码（缺失身体返回 null）
function processAnimFile(file) {
  const filePath = path.join(animDir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const animKey = path.basename(file, '.json').toLowerCase(); // 101, 102, 102s 等
  const baseKey = animKey.replace(/s$/i, "");

  console.log(`Processing animation: ${file} -> Key: ${animKey}`);

  // ===== 身体层识别 =====
  // SVGator 导出图层（ty=2 图像层）顺序：第一层武器、第二层怪兽身体、第三层武器…
  // 判别标准：身体层缩放为 100%（无 s 或 s=[100,100]），武器层通常有缩放（6%~32%）。
  // 若多层缩放相同（如 124 全部 100%），取中间层为身体（第二层是怪兽）。
  const assetById = new Map(data.assets.map(a => [a.id, a]));
  const imageLayers = data.layers.filter(l => l.ty === 2 && l.refId && assetById.has(l.refId));
  if (imageLayers.length === 0) {
    console.warn(`  Warning: No image layer in ${file}`);
    return null;
  }

  let bodyIdx = 0;
  const diffs = imageLayers.map(l => Math.abs(layerScale(l) - 100));
  const minDiff = Math.min(...diffs);
  const candidates = diffs.map((d, i) => ({ i, d })).filter(c => c.d === minDiff);
  bodyIdx = candidates[Math.floor((candidates.length - 1) / 2)].i; // 并列时取中间层
  const bodyLayer = imageLayers[bodyIdx];
  const bodyAsset = assetById.get(bodyLayer.refId);
  console.log(`  Body layer: [${data.layers.indexOf(bodyLayer)}] refId=${bodyLayer.refId} (${bodyAsset.w}x${bodyAsset.h}, scale=${layerScale(bodyLayer)})`);

  // 武器层 = 其余图像层，按 Lottie 索引顶层→底层排列（第一层武器=贴图-1）
  let weaponLayers = imageLayers.filter((_, i) => i !== bodyIdx);
  weaponLayers = weaponLayers.sort((a, b) => data.layers.indexOf(a) - data.layers.indexOf(b));
  // 手动顺序矫正（个别动画贴图命名与图层层级不同）
  const orderTweak = WEAPON_ORDER_TWEAKS[baseKey];
  if (orderTweak) {
    weaponLayers = orderTweak
      .map(id => weaponLayers.find(l => l.refId === id))
      .filter(Boolean);
    console.log(`  Weapon order (tweak): ${weaponLayers.map(l => l.refId).join(', ')}`);
  }
  console.log(`  Weapon layers: ${weaponLayers.map(l => `[${data.layers.indexOf(l)}]${l.refId}`).join(', ')}`);

  // 身体图层位置 (p)：武器/身体 positions 相对它的偏移基准
  let bodyX = 0;
  let bodyY = 0;
  if (bodyLayer.ks && bodyLayer.ks.p) {
    const bp = bodyLayer.ks.p;
    if (bp.a === 0 && Array.isArray(bp.k)) {
      bodyX = bp.k[0];
      bodyY = bp.k[1];
    } else if (bp.a === 1 && Array.isArray(bp.k) && bp.k[0] && Array.isArray(bp.k[0].s)) {
      bodyX = bp.k[0].s[0];
      bodyY = bp.k[0].s[1];
    }
  }
  console.log(`  Body center: [${bodyX}, ${bodyY}]`);

  // 身体尺寸 = 身体资产原始像素（不乘图层缩放：游戏里身体固定按 sw 显示，
  // k = displayW / 原尺寸；图层缩放只影响 comp 内的相对位置，不影响换算基准）
  const compBodyW = bodyAsset.w || 40;
  const compBodyH = bodyAsset.h || 40;

  // 身体锚点 (a)：武器位置换算基准
  let bodyAnchorX = compBodyW / 2;
  let bodyAnchorY = compBodyH / 2;
  if (bodyLayer.ks && bodyLayer.ks.a) {
    const bpa = bodyLayer.ks.a;
    if (bpa.a === 0 && Array.isArray(bpa.k)) {
      bodyAnchorX = bpa.k[0];
      bodyAnchorY = bpa.k[1];
    } else if (bpa.a === 1 && Array.isArray(bpa.k) && bpa.k[0] && Array.isArray(bpa.k[0].s)) {
      bodyAnchorX = bpa.k[0].s[0];
      bodyAnchorY = bpa.k[0].s[1];
    }
  }
  console.log(`  Body anchor: [${bodyAnchorX}, ${bodyAnchorY}]`);

  // 身体图层缩放 (s)：武器比例换算需除以它（身体 18% 时武器 100% 相对身体就是 100/18 倍）
  let bodyScaleX = 100;
  let bodyScaleY = 100;
  if (bodyLayer.ks && bodyLayer.ks.s) {
    const bs = bodyLayer.ks.s;
    if (bs.a === 0 && Array.isArray(bs.k)) {
      bodyScaleX = bs.k[0];
      bodyScaleY = bs.k[1];
    } else if (bs.a === 1 && Array.isArray(bs.k) && bs.k[0] && Array.isArray(bs.k[0].s)) {
      bodyScaleX = bs.k[0].s[0];
      bodyScaleY = bs.k[0].s[1];
    }
  }
  console.log(`  Body layer scale: [${bodyScaleX}, ${bodyScaleY}]`);

  // 收集武器层数据（贴图尺寸/缩放/锚点/轨道）
  const weapons = weaponLayers.map(layer => {
    const asset = assetById.get(layer.refId);
    return extractWeapon(asset, layer, bodyX, bodyY);
  });
  // 应用手动锚点矫正（主武器；双武器如需矫正可扩展数组）
  if (weapons.length > 0 && ANCHOR_TWEAKS[baseKey]) {
    applyAnchorTweak(weapons[0], ANCHOR_TWEAKS[baseKey]);
  }
  if (weapons.length === 0) {
    console.warn(`  Warning: No weapon layer in ${file}`);
    return null;
  }

  // 导出武器贴图：统一按序号命名 asset_1 → {base}-1.png，asset_2 → {base}-2.png …
  // 已有同名文件跳过，避免覆盖用户手动放置/微调过的贴图。
  weapons.forEach((w, i) => {
    if (!w.base64) return;
    const imgPath = path.join(weaponsDir, `${baseKey}-${i + 1}.png`);
    if (fs.existsSync(imgPath)) {
      console.log(`  Skip (exists): ${imgPath}`);
      return;
    }
    fs.writeFileSync(imgPath, w.base64, 'base64');
    console.log(`  Saved weapon texture: ${imgPath}`);
  });

  const duration = data.op || 80;

  // 裁剪尾部静止帧：去掉末尾无新动作的重复关键帧，并相应缩短动画时长
  const trimmedBodyTracks = trimTracks(extractLayerTracks(bodyLayer, bodyX, bodyY));
  const trimmedWeapons = weapons.map(w => ({ ...w, tracks: trimTracks(w.tracks) }));
  const trimmedDuration = computeTrimmedDuration(
    duration,
    trimmedBodyTracks.positions, trimmedBodyTracks.rotations, trimmedBodyTracks.opacities,
    ...trimmedWeapons.flatMap(w => [w.tracks.positions, w.tracks.rotations, w.tracks.opacities])
  );
  if (trimmedDuration !== duration) {
    console.log(`  Duration: ${duration} -> ${trimmedDuration} (尾部静止帧裁剪)`);
  }

  let code = `  "${animKey}": {
    duration: ${trimmedDuration},
    body: {
      size: { x: ${compBodyW}, y: ${compBodyH} },
      scale: { x: ${bodyScaleX}, y: ${bodyScaleY} },
      anchor: { x: ${bodyAnchorX}, y: ${bodyAnchorY} },
      tracks: {
        positions: ${JSON.stringify(trimmedBodyTracks.positions)},
        rotations: ${JSON.stringify(trimmedBodyTracks.rotations)},
        opacities: ${JSON.stringify(trimmedBodyTracks.opacities)}
      }
    },
    weapons: [
`;
  for (const w of trimmedWeapons) {
    code += renderWeapon(w);
  }
  code += `    ],
  },
`;
  return code;
}

// ==================== 主流程 ====================

const isIncremental = process.argv.includes('--incremental');
const updateArg = process.argv.find(a => a.startsWith('--update='));
const updateKeys = updateArg ? new Set(updateArg.slice('--update='.length).split(',')) : new Set();

const existingKeys = readExistingKeys();
const allFiles = fs.readdirSync(animDir).filter(f => f.endsWith('.json'));

let targetFiles;
if (updateKeys.size > 0) {
  // 更新指定 key：即使已存在也重新生成并替换（如修复 108/110 双武器）
  targetFiles = allFiles.filter(f => updateKeys.has(path.basename(f, '.json').toLowerCase()));
} else if (isIncremental) {
  // 增量：只处理新增动画（key 尚未出现），其余保持不动（保留用户微调）
  targetFiles = allFiles.filter(f => !existingKeys.has(path.basename(f, '.json').toLowerCase()));
} else {
  targetFiles = allFiles;
}

const entries = [];
for (const file of targetFiles) {
  const entry = processAnimFile(file);
  if (entry) entries.push(entry);
}

if (updateKeys.size > 0) {
  // 替换输出文件中对应 key 的条目
  let content = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, 'utf8') : header;
  for (const key of updateKeys) {
    const regex = new RegExp(`^  "${key}": \\{[\\s\\S]*?\\n  \\},\\n`, 'm');
    const entry = entries.find(e => e.startsWith(`  "${key}": {`));
    if (!entry) continue;
    if (regex.test(content)) {
      content = content.replace(regex, entry);
      console.log(`  Updated existing entry: ${key}`);
    } else {
      content = content.replace(/\}\s*;\s*$/, `${entry}};\n`);
      console.log(`  Appended entry: ${key}`);
    }
  }
  fs.writeFileSync(outputFile, content, 'utf8');
  console.log(`\nUpdate: refreshed ${entries.length} animations (${Array.from(updateKeys).join(', ')})`);
} else if (isIncremental) {
  // 增量模式：只追加新条目，已有内容（含用户微调）原样保留
  let content = fs.readFileSync(outputFile, 'utf8');
  content = content.replace(/\}\s*;\s*$/, `${entries.join('')}};\n`);
  fs.writeFileSync(outputFile, content, 'utf8');
  console.log(`\nIncremental: added ${entries.length} new animations to AnimationData.ts`);
} else {
  const generatedCode = header + entries.join('') + `};\n`;
  fs.writeFileSync(outputFile, generatedCode, 'utf8');
  console.log(`\nSuccessfully generated AnimationData.ts! Total animations: ${targetFiles.length}`);
}
