/**
 * This file is automatically generated by scripts/animation/parse_animations.js
 * DO NOT EDIT MANUALLY!
 */

export interface Keyframe<T> {
  t: number;
  value: T;
}

/** 单层（身体/武器）的变换关键帧轨道 */
export interface LayerTracks {
  positions: Keyframe<{ x: number; y: number }>[];
  rotations: Keyframe<number>[];
  /** 透明度关键帧（0~100，100=不透明），用于武器贴图切换/淡入淡出；无动画时为空数组 */
  opacities: Keyframe<number>[];
}

/** 武器层：贴图尺寸 + 缩放/锚点 + 变换轨道 */
export interface WeaponLayer {
  /** 武器贴图原始尺寸（像素），用于锚点归一化 */
  size: { x: number; y: number };
  /** 武器缩放（百分比，如 6 代表 6%） */
  scale: { x: number; y: number };
  /** 武器旋转中心锚点（贴图像素坐标） */
  anchor: { x: number; y: number };
  tracks: LayerTracks;
}

/**
 * 统一动画剪辑：一次动画 = 身体层 + 一到多个武器层（weapons 数组）。
 * 身体层描述贴图尺寸/锚点/图层缩放与身体变换；各武器层 positions 均为相对身体锚点的偏移（comp 像素，y 向下）。
 * 武器层数量 = 动画中武器个数（1 个主武器、2 个双武器、3 个双手武器…），贴图按 {dbId}-1.png / {dbId}-2.png / {dbId}-3.png 顺序对应。
 */
export interface AnimationClip {
  /** 动画总时长（帧，100fps） */
  duration: number;
  body: {
    /** 身体贴图原始尺寸（像素），用于把 comp 坐标换算到游戏本地坐标 */
    size: { x: number; y: number };
    /** 身体图层缩放（百分比，SVGator 层缩放；武器比例换算需除以它，如救星骑士 18%） */
    scale: { x: number; y: number };
    /** 身体层变换锚点（asset 像素坐标） */
    anchor: { x: number; y: number };
    /**
     * 动画整体旋转中心（asset 像素坐标，与 anchor 同语义）。
     * 身体 rotation 关键帧旋转时绕该点转；缺省 = 身体几何中心（size/2，即"身体中间"）。
     * 一般无需配置；个别怪若需绕其他点（如脚底）旋转再填。
     */
    rotCenter?: { x: number; y: number };
    tracks: LayerTracks;
  };
  /** 武器层数组（主武器 + 第二/三武器…），数量可变 */
  weapons: WeaponLayer[];
}

export const ANIMATIONS: Record<string, AnimationClip> = {
  "101": {
    duration: 71,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 32.44 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":10,"value":32040},{"t":20,"value":32032.61},{"t":50,"value":32047.64},{"t":70,"value":32040}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 348, y: 252 },
        scale: { x: 6, y: 6 },
        anchor: { x: 48, y: 126 },
        tracks: {
          positions: [{"t":0,"value":{"x":0,"y":-2}},{"t":20,"value":{"x":-9.61,"y":-5}},{"t":30,"value":{"x":1.94,"y":-3.69}},{"t":40,"value":{"x":9.49,"y":1.62}},{"t":50,"value":{"x":-7.25,"y":2.72}},{"t":70,"value":{"x":0,"y":-2}}],
          rotations: [{"t":0,"value":0},{"t":20,"value":-146.97},{"t":50,"value":125.6},{"t":70,"value":-3.66}],
          opacities: []
        }
      },
    ],
  },
  "102": {
    duration: 61,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 33.5556 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 348, y: 108 },
        scale: { x: 8, y: 8 },
        anchor: { x: 103.013587, y: 54 },
        tracks: {
          positions: [{"t":0,"value":{"x":-8.4,"y":-0.83}},{"t":20,"value":{"x":-10.96,"y":-4.35}},{"t":40,"value":{"x":10,"y":-1.61}},{"t":60,"value":{"x":-8.4,"y":-0.83}}],
          rotations: [{"t":0,"value":-90},{"t":20,"value":-123.25},{"t":40,"value":-12.91},{"t":60,"value":-90}],
          opacities: []
        }
      },
    ],
  },
  "102s": {
    duration: 170,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 33.5556 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 348, y: 108 },
        scale: { x: 8, y: 8 },
        anchor: { x: 103.013587, y: 54 },
        tracks: {
          positions: [{"t":0,"value":{"x":-8.4,"y":-0.83}},{"t":20,"value":{"x":7.26,"y":-7.06}},{"t":50,"value":{"x":9.14,"y":-7.88}},{"t":80,"value":{"x":7.14,"y":-7.88}},{"t":110,"value":{"x":-10.04,"y":-8.13}},{"t":130,"value":{"x":14.44,"y":3.31}},{"t":170,"value":{"x":-8.4,"y":-0.83}}],
          rotations: [{"t":0,"value":-90},{"t":20,"value":-75.38},{"t":50,"value":-89.28},{"t":80,"value":-75.38},{"t":110,"value":-107.32},{"t":130,"value":11.54},{"t":170,"value":-90}],
          opacities: []
        }
      },
    ],
  },
  "103": {
    duration: 51,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 336, y: 84 },
        scale: { x: 8, y: 8 },
        anchor: { x: 168, y: 42 },
        tracks: {
          positions: [{"t":0,"value":{"x":-7.65,"y":6.24}},{"t":15,"value":{"x":-12.84,"y":3.06}},{"t":35,"value":{"x":11.67,"y":7.18}},{"t":50,"value":{"x":-7.65,"y":6.24}}],
          rotations: [{"t":0,"value":-90},{"t":15,"value":-100.56},{"t":35,"value":-47.42},{"t":50,"value":-90}],
          opacities: []
        }
      },
    ],
  },
  "103s": {
    duration: 250,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 336, y: 84 },
        scale: { x: 8, y: 8 },
        anchor: { x: 168, y: 42 },
        tracks: {
          positions: [{"t":0,"value":{"x":-7.65,"y":6.24}},{"t":10,"value":{"x":-7.51,"y":-2}},{"t":30,"value":{"x":-7.58,"y":-1.88}},{"t":245,"value":{"x":-7.58,"y":-1.88}},{"t":250,"value":{"x":-7.65,"y":6.24}}],
          rotations: [{"t":0,"value":-90}],
          opacities: []
        }
      },
    ],
  },
  "104": {
    duration: 41,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 288, y: 96 },
        scale: { x: 8, y: 8 },
        anchor: { x: 66, y: 48 },
        tracks: {
          positions: [{"t":0,"value":{"x":-1,"y":14}},{"t":10,"value":{"x":-10.02,"y":12.82}},{"t":30,"value":{"x":-0.01,"y":13.61}},{"t":40,"value":{"x":-1,"y":14}}],
          rotations: [{"t":0,"value":0},{"t":10,"value":-9.54},{"t":30,"value":4.83},{"t":40,"value":0}],
          opacities: []
        }
      },
    ],
  },
  "104s": {
    duration: 91,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 288, y: 96 },
        scale: { x: 8, y: 8 },
        anchor: { x: 66, y: 48 },
        tracks: {
          positions: [{"t":0,"value":{"x":-1,"y":14}},{"t":20,"value":{"x":-4.82,"y":13.61}},{"t":40,"value":{"x":-1,"y":14}},{"t":50,"value":{"x":-1,"y":14}},{"t":60,"value":{"x":-10.02,"y":12.82}},{"t":80,"value":{"x":-0.01,"y":13.61}},{"t":90,"value":{"x":-1,"y":14}}],
          rotations: [{"t":0,"value":-358.37},{"t":40,"value":0},{"t":50,"value":0},{"t":60,"value":-9.54},{"t":80,"value":4.83},{"t":90,"value":0}],
          opacities: []
        }
      },
    ],
  },
  "105": {
    duration: 61,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 336, y: 84 },
        scale: { x: 8, y: 8 },
        anchor: { x: 168, y: 42 },
        tracks: {
          positions: [{"t":0,"value":{"x":-8.48,"y":6.56}},{"t":20,"value":{"x":-13.88,"y":5.16}},{"t":30,"value":{"x":2,"y":5.26}},{"t":50,"value":{"x":-9.48,"y":6.56}},{"t":60,"value":{"x":-8.48,"y":6.56}}],
          rotations: [{"t":0,"value":-90},{"t":20,"value":-106.91},{"t":30,"value":-68.56},{"t":50,"value":-95.93},{"t":60,"value":-90}],
          opacities: []
        }
      },
    ],
  },
  "106": {
    duration: 60,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 396, y: 96 },
        scale: { x: 8, y: 8 },
        anchor: { x: 198, y: 48 },
        tracks: {
          positions: [{"t":0,"value":{"x":1.16,"y":10.48}},{"t":16,"value":{"x":-4.82,"y":12.3}},{"t":27,"value":{"x":21.34,"y":11.64}},{"t":59,"value":{"x":1.16,"y":10.48}}],
          rotations: [{"t":0,"value":-19.27},{"t":16,"value":-6.85},{"t":27,"value":0},{"t":59,"value":-19.27}],
          opacities: []
        }
      },
    ],
  },
  // 106s：冲锋哥技能动画（冲锋前摇）——身体后仰摇摆蓄力 → 保持 → 前倾猛冲（武器相对身体固定）。
  // 时长 60 帧 = 0.6s，与 AnimTuning.RUSH_WINDUP 前摇时长对齐。
  "106s": {
    duration: 60,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":20,"value":-20},{"t":30,"value":-20},{"t":60,"value":15}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 396, y: 96 },
        scale: { x: 8, y: 8 },
        anchor: { x: 198, y: 48 },
        tracks: {
          positions: [{"t":0,"value":{"x":1.16,"y":10.48}}],
          rotations: [{"t":0,"value":-19.27}],
          opacities: []
        }
      },
    ],
  },
  "107": {
    duration: 62,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 336, y: 60 },
        scale: { x: 8, y: 8 },
        anchor: { x: 168, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":-8,"y":6.24}},{"t":16,"value":{"x":-13,"y":1.24}},{"t":31,"value":{"x":11.5,"y":5.74}},{"t":61,"value":{"x":-8,"y":6.24}}],
          rotations: [{"t":0,"value":-810},{"t":16,"value":-827.74},{"t":31,"value":-763.14},{"t":61,"value":-810}],
          opacities: []
        }
      },
    ],
  },
  "107s": {
    duration: 223,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 336, y: 60 },
        scale: { x: 8, y: 8 },
        anchor: { x: 168, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":-8,"y":6.24}},{"t":22,"value":{"x":5.5,"y":11.74}},{"t":200,"value":{"x":5.5,"y":11.74}},{"t":223,"value":{"x":-8,"y":6.24}}],
          rotations: [{"t":0,"value":-810},{"t":22,"value":-763.14},{"t":200,"value":-763.14},{"t":223,"value":-810}],
          opacities: []
        }
      },
    ],
  },
  "108": {
    duration: 103,
    body: {
      size: { x: 31, y: 34 },
      scale: { x: 100, y: 100 },
      anchor: { x: 15.5, y: 17 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}},{"t":15,"value":{"x":-2,"y":0}},{"t":30,"value":{"x":-1,"y":0}},{"t":45,"value":{"x":2.17,"y":0.17}},{"t":60,"value":{"x":0,"y":0}},{"t":72,"value":{"x":0,"y":0}},{"t":87,"value":{"x":3.17,"y":0.17}},{"t":102,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":15,"value":-7.31},{"t":30,"value":-4.76},{"t":45,"value":3.97},{"t":60,"value":0},{"t":72,"value":0},{"t":87,"value":6.48},{"t":102,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 78, y: 60 },
        scale: { x: 18, y: 18 },
        anchor: { x: 39, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":-4.8,"y":7.22}},{"t":10,"value":{"x":-12.8,"y":7.22}},{"t":20,"value":{"x":-12.8,"y":7.22}},{"t":35,"value":{"x":21.92,"y":7.22}},{"t":50,"value":{"x":-4.8,"y":7.22}}],
          rotations: [{"t":0,"value":-32.85},{"t":10,"value":-7.62},{"t":20,"value":-22.61},{"t":35,"value":-0.31},{"t":50,"value":-32.85}],
          opacities: []
        }
      },
      {
        size: { x: 72, y: 60 },
        scale: { x: 18, y: 18 },
        anchor: { x: 36, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":12.02,"y":6.22}},{"t":10,"value":{"x":14.02,"y":6.22}},{"t":72,"value":{"x":12.02,"y":6.22}},{"t":87,"value":{"x":28.02,"y":8.22}},{"t":102,"value":{"x":12.02,"y":6.22}}],
          rotations: [{"t":0,"value":-35.38},{"t":72,"value":-35.38},{"t":87,"value":-2.58},{"t":102,"value":-35.38}],
          opacities: []
        }
      },
    ],
  },
  "109": {
    duration: 231,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 348, y: 108 },
        scale: { x: 8, y: 8 },
        anchor: { x: 174, y: 54 },
        tracks: {
          positions: [{"t":0,"value":{"x":8.08,"y":13.68}},{"t":10,"value":{"x":8.08,"y":10.68}},{"t":200,"value":{"x":8.08,"y":10.68}},{"t":210,"value":{"x":-0.92,"y":9.97}},{"t":230,"value":{"x":8.08,"y":13.68}}],
          rotations: [{"t":200,"value":0},{"t":210,"value":-14.57},{"t":230,"value":0}],
          opacities: []
        }
      },
    ],
  },
  "110": {
    duration: 42,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 192, y: 204 },
        scale: { x: 8, y: 8 },
        anchor: { x: 96, y: 102 },
        tracks: {
          positions: [{"t":0,"value":{"x":-7.32,"y":9.84}}],
          rotations: [],
          opacities: [{"t":0,"value":100},{"t":9,"value":100},{"t":10,"value":0},{"t":40,"value":0},{"t":41,"value":100}]
        }
      },
      {
        size: { x: 168, y: 204 },
        scale: { x: 8, y: 8 },
        anchor: { x: 84, y: 102 },
        tracks: {
          positions: [{"t":10,"value":{"x":-6.72,"y":9.84}},{"t":25,"value":{"x":22.28,"y":9.84}},{"t":40,"value":{"x":-6.72,"y":9.84}}],
          rotations: [],
          opacities: [{"t":9,"value":0},{"t":10,"value":100},{"t":40,"value":100},{"t":41,"value":0}]
        }
      },
    ],
  },
  "110s": {
    duration: 35,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 192, y: 204 },
        scale: { x: 8, y: 8 },
        anchor: { x: 96, y: 102 },
        tracks: {
          positions: [{"t":0,"value":{"x":-7.32,"y":9.84}},{"t":17,"value":{"x":-7.32,"y":0.84}},{"t":34,"value":{"x":-7.32,"y":9.84}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "111": {
    duration: 86,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}},{"t":20,"value":{"x":-3,"y":0}},{"t":29,"value":{"x":-3,"y":0}},{"t":40,"value":{"x":-0.61,"y":0.2}},{"t":85,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":20,"value":-7.78},{"t":29,"value":-14.04},{"t":40,"value":6.16},{"t":85,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 288, y: 120 },
        scale: { x: 9, y: 9 },
        anchor: { x: 144, y: 60 },
        tracks: {
          positions: [{"t":0,"value":{"x":9.04,"y":14.6}},{"t":15,"value":{"x":-16.55,"y":-5.85}},{"t":25,"value":{"x":-16.55,"y":-5.85}},{"t":35,"value":{"x":21.97,"y":9.45}},{"t":45,"value":{"x":-7.3,"y":32.13}},{"t":54,"value":{"x":-15.51,"y":23.6}},{"t":85,"value":{"x":9.04,"y":14.6}}],
          rotations: [{"t":0,"value":-14.49},{"t":15,"value":-150.68},{"t":25,"value":-150.68},{"t":35,"value":-24.5},{"t":45,"value":92.1},{"t":54,"value":155.93},{"t":85,"value":-14.49}],
          opacities: []
        }
      },
    ],
  },
  "112": {
    duration: 173,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 38 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":31,"value":-7.68},{"t":45,"value":-7.22},{"t":76,"value":33.3},{"t":106,"value":-0.32},{"t":172,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 372, y: 84 },
        scale: { x: 8, y: 8 },
        anchor: { x: 30, y: 42 },
        tracks: {
          positions: [{"t":0,"value":{"x":-2.98,"y":-2.1}},{"t":31,"value":{"x":-8.02,"y":4.55}},{"t":45,"value":{"x":-8.02,"y":4.55}},{"t":56,"value":{"x":-12.18,"y":-14.58}},{"t":66,"value":{"x":15.13,"y":-1.86}},{"t":76,"value":{"x":14.07,"y":3.97}},{"t":122,"value":{"x":-2.98,"y":-2.1}}],
          rotations: [{"t":0,"value":-11},{"t":31,"value":99.92},{"t":45,"value":112.19},{"t":56,"value":221.76},{"t":66,"value":355.78},{"t":76,"value":370.39},{"t":100,"value":365.19},{"t":122,"value":339}],
          opacities: []
        }
      },
    ],
  },
  "112s": {
    duration: 225,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 38 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":22,"value":0},{"t":48,"value":-8.12},{"t":62,"value":-8.12},{"t":80,"value":11.21},{"t":143,"value":11.21},{"t":171,"value":-9.5},{"t":208,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 372, y: 84 },
        scale: { x: 8, y: 8 },
        anchor: { x: 30, y: 42 },
        tracks: {
          positions: [{"t":0,"value":{"x":-2.98,"y":-2.1}},{"t":22,"value":{"x":5.97,"y":-16.38}},{"t":62,"value":{"x":3.71,"y":-22.55}},{"t":80,"value":{"x":12.86,"y":-5.89}},{"t":143,"value":{"x":12.86,"y":-5.89}},{"t":171,"value":{"x":7.51,"y":-30.79}},{"t":224,"value":{"x":-2.98,"y":-2.1}}],
          rotations: [{"t":0,"value":-11},{"t":22,"value":-115.51},{"t":48,"value":-301.55},{"t":62,"value":-301.55},{"t":80,"value":-270.61},{"t":143,"value":-270.61},{"t":171,"value":-288.73},{"t":224,"value":-11}],
          opacities: []
        }
      },
    ],
  },
  "113": {
    duration: 51,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 87, y: 56 },
        scale: { x: 20, y: 20 },
        anchor: { x: 43.5, y: 28 },
        tracks: {
          positions: [{"t":0,"value":{"x":0,"y":11.2}},{"t":10,"value":{"x":-8,"y":12.2}},{"t":25,"value":{"x":12.43,"y":3.92}},{"t":50,"value":{"x":0,"y":11.2}}],
          rotations: [{"t":0,"value":-20.16}],
          opacities: []
        }
      },
    ],
  },
  "114": {
    duration: 1,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 312, y: 144 },
        scale: { x: 8, y: 8 },
        anchor: { x: 156, y: 72 },
        tracks: {
          positions: [{"t":0,"value":{"x":5.960000000000001,"y":13.000000000000002}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "115": {
    duration: 101,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 38.54 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":33,"value":-3.05},{"t":43,"value":-3.68},{"t":53,"value":7.93},{"t":79,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 300, y: 108 },
        scale: { x: 9, y: 9 },
        anchor: { x: 33.71, y: 54 },
        tracks: {
          positions: [{"t":0,"value":{"x":0,"y":-4.86}},{"t":17,"value":{"x":-10.64,"y":-4.13}},{"t":33,"value":{"x":-6.2,"y":-10.99}},{"t":43,"value":{"x":-8.38,"y":-11.85}},{"t":58,"value":{"x":14.39,"y":-2.3}},{"t":100,"value":{"x":0,"y":-4.86}}],
          rotations: [{"t":0,"value":0},{"t":17,"value":-19.08},{"t":33,"value":-130.33},{"t":43,"value":-151.45},{"t":58,"value":-1.96},{"t":100,"value":0}],
          opacities: []
        }
      },
    ],
  },
  "115s": {
    duration: 91,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 38.54 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 300, y: 108 },
        scale: { x: 9, y: 9 },
        anchor: { x: 33.71, y: 54 },
        tracks: {
          positions: [{"t":0,"value":{"x":2,"y":-4.86}},{"t":10,"value":{"x":-2,"y":-4.86}},{"t":30,"value":{"x":-2,"y":-22.86}},{"t":40,"value":{"x":-2,"y":-16.48}},{"t":50,"value":{"x":-2,"y":-22.86}},{"t":70,"value":{"x":-2,"y":-22.86}},{"t":90,"value":{"x":2,"y":-4.86}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "116": {
    duration: 381,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 288, y: 132 },
        scale: { x: 8, y: 8 },
        anchor: { x: 144, y: 66 },
        tracks: {
          positions: [{"t":0,"value":{"x":5.6,"y":13.4}},{"t":10,"value":{"x":14.6,"y":13.4}},{"t":370,"value":{"x":14.6,"y":13.4}},{"t":380,"value":{"x":5.6,"y":13.4}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "117": {
    duration: 91,
    body: {
      size: { x: 32, y: 32 },
      scale: { x: 100, y: 100 },
      anchor: { x: 16, y: 29.961839 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":20,"value":-6.42},{"t":34,"value":-6.42},{"t":47,"value":12.41},{"t":53,"value":12.41},{"t":71,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 66, y: 60 },
        scale: { x: 17, y: 17 },
        anchor: { x: 33, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":-7.67,"y":-7.54}},{"t":20,"value":{"x":-15.67,"y":-8.54}},{"t":34,"value":{"x":-15.67,"y":-8.54}},{"t":47,"value":{"x":21.33,"y":-7.54}},{"t":53,"value":{"x":21.33,"y":-7.54}},{"t":90,"value":{"x":-7.67,"y":-7.54}}],
          rotations: [{"t":0,"value":-41.39}],
          opacities: []
        }
      },
      {
        size: { x: 72, y: 60 },
        scale: { x: 17, y: 17 },
        anchor: { x: 36, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":12.75,"y":-9.42}},{"t":20,"value":{"x":15.75,"y":-9.42}},{"t":34,"value":{"x":15.75,"y":-9.42}},{"t":47,"value":{"x":2.75,"y":-9.42}},{"t":53,"value":{"x":2.75,"y":-9.42}},{"t":90,"value":{"x":12.75,"y":-9.42}}],
          rotations: [{"t":0,"value":-34.5}],
          opacities: []
        }
      },
    ],
  },
  "117s": {
    duration: 91,
    body: {
      size: { x: 32, y: 32 },
      scale: { x: 100, y: 100 },
      anchor: { x: 16, y: 29.961839 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":20,"value":-23.63},{"t":40,"value":-23.63},{"t":60,"value":13.83},{"t":70,"value":18.04},{"t":90,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 66, y: 60 },
        scale: { x: 17, y: 17 },
        anchor: { x: 33, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":-7.67,"y":-7.77}},{"t":20,"value":{"x":-25.63,"y":-10.04}},{"t":40,"value":{"x":-25.63,"y":-10.04}},{"t":60,"value":{"x":18.01,"y":-29.19}},{"t":90,"value":{"x":-7.67,"y":-7.77}}],
          rotations: [{"t":0,"value":-41.39},{"t":20,"value":-189.07},{"t":40,"value":-189.07},{"t":60,"value":-74.49}],
          opacities: []
        }
      },
      {
        size: { x: 72, y: 60 },
        scale: { x: 17, y: 17 },
        anchor: { x: 36, y: 30 },
        tracks: {
          positions: [{"t":0,"value":{"x":12.75,"y":-9.65}},{"t":20,"value":{"x":-19.64,"y":-19.57}},{"t":40,"value":{"x":-19.64,"y":-19.57}},{"t":60,"value":{"x":30.83,"y":-33.12}},{"t":90,"value":{"x":12.75,"y":-9.65}}],
          rotations: [{"t":0,"value":-34.5},{"t":20,"value":-164.51},{"t":40,"value":-164.51},{"t":60,"value":-56.82}],
          opacities: []
        }
      },
    ],
  },
  "118": {
    duration: 82,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 252, y: 96 },
        scale: { x: 9, y: 9 },
        anchor: { x: 46.647741, y: 48 },
        tracks: {
          positions: [{"t":0,"value":{"x":8.2,"y":14.68}},{"t":19,"value":{"x":-4.18,"y":11.23}},{"t":30,"value":{"x":-4.18,"y":11.23}},{"t":40,"value":{"x":20.25,"y":17.17}},{"t":50,"value":{"x":0.6,"y":17.23}},{"t":81,"value":{"x":8.2,"y":14.68}}],
          rotations: [{"t":0,"value":0},{"t":19,"value":-111.27},{"t":30,"value":-111.27},{"t":50,"value":132.85},{"t":81,"value":0}],
          opacities: []
        }
      },
    ],
  },
  "119": {
    duration: 68,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 168, y: 108 },
        scale: { x: 8, y: 8 },
        anchor: { x: 84, y: 54 },
        tracks: {
          positions: [{"t":0,"value":{"x":7.4,"y":12.6}},{"t":15,"value":{"x":-2.6,"y":12.6}},{"t":23,"value":{"x":-2.6,"y":12.6}},{"t":33,"value":{"x":23.4,"y":12.6}},{"t":43,"value":{"x":23.4,"y":12.6}},{"t":67,"value":{"x":7.4,"y":12.6}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "120": {
    duration: 161,
    body: {
      size: { x: 33, y: 33 },
      scale: { x: 100, y: 100 },
      anchor: { x: 16.5, y: 16.5 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 96, y: 32 },
        scale: { x: 32, y: 32 },
        anchor: { x: 48, y: 16 },
        tracks: {
          positions: [{"t":0,"value":{"x":3.12,"y":10}},{"t":10,"value":{"x":-2.52,"y":10}},{"t":30,"value":{"x":0.48,"y":10}},{"t":40,"value":{"x":-2.52,"y":10}},{"t":60,"value":{"x":0.48,"y":10}},{"t":70,"value":{"x":-2.52,"y":10}},{"t":90,"value":{"x":0.48,"y":10}},{"t":100,"value":{"x":-2.52,"y":10}},{"t":120,"value":{"x":0.48,"y":10}},{"t":130,"value":{"x":-2.52,"y":10}},{"t":150,"value":{"x":0.48,"y":10}},{"t":160,"value":{"x":3.12,"y":10}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "121": {
    duration: 1,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 98, y: 80 },
        scale: { x: 10, y: 10 },
        anchor: { x: 49, y: 40 },
        tracks: {
          positions: [{"t":0,"value":{"x":1,"y":6.713384999999999}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "122": {
    duration: 1,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 180, y: 156 },
        scale: { x: 8, y: 8 },
        anchor: { x: 90, y: 78 },
        tracks: {
          positions: [{"t":0,"value":{"x":4,"y":14.200000000000003}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "123": {
    duration: 70,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 35.947243 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":22,"value":-10.88},{"t":29,"value":-10.88},{"t":39,"value":5.54},{"t":69,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 312, y: 60 },
        scale: { x: 8, y: 8 },
        anchor: { x: 29.071849, y: 33.461071 },
        tracks: {
          positions: [{"t":0,"value":{"x":0,"y":-1.9}},{"t":22,"value":{"x":-7.15,"y":-7.58}},{"t":29,"value":{"x":-7.15,"y":-7.58}},{"t":39,"value":{"x":16.34,"y":1.86}},{"t":49,"value":{"x":-0.39,"y":3.15}},{"t":69,"value":{"x":0,"y":-1.9}}],
          rotations: [{"t":0,"value":-11.81},{"t":22,"value":-139.64},{"t":29,"value":-139.64},{"t":39,"value":-2.85},{"t":49,"value":129.14},{"t":69,"value":-11.81}],
          opacities: []
        }
      },
    ],
  },
  "124": {
    duration: 82,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 20 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 9, y: 11 },
        scale: { x: 100, y: 100 },
        anchor: { x: 4.5, y: 2.5 },
        tracks: {
          positions: [{"t":0,"value":{"x":-6.69,"y":10}},{"t":31,"value":{"x":-6.69,"y":8}},{"t":44,"value":{"x":-6.69,"y":8}},{"t":50,"value":{"x":-2.69,"y":8}},{"t":62,"value":{"x":-3.69,"y":12}},{"t":81,"value":{"x":-6.69,"y":10}}],
          rotations: [{"t":0,"value":0},{"t":31,"value":-242.98},{"t":44,"value":-242.98},{"t":50,"value":-158.59},{"t":62,"value":-74.98},{"t":81,"value":0}],
          opacities: []
        }
      },
      {
        size: { x: 8, y: 11 },
        scale: { x: 100, y: 100 },
        anchor: { x: 4, y: 5.5 },
        tracks: {
          positions: [{"t":0,"value":{"x":10,"y":13}}],
          rotations: [],
          opacities: []
        }
      },
    ],
  },
  "124s": {
    duration: 101,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 37 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":25,"value":-18.95},{"t":40,"value":-18.95},{"t":60,"value":7.56},{"t":100,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 9, y: 11 },
        scale: { x: 100, y: 100 },
        anchor: { x: 4.5, y: 2.5 },
        tracks: {
          positions: [{"t":0,"value":{"x":-6.69,"y":-7}},{"t":20,"value":{"x":-13.41,"y":-8.93}},{"t":40,"value":{"x":-13.41,"y":-8.93}},{"t":60,"value":{"x":12.13,"y":-16.66}},{"t":80,"value":{"x":5.72,"y":-5.58}},{"t":100,"value":{"x":-6.69,"y":-7}}],
          rotations: [{"t":0,"value":0},{"t":20,"value":-246.26},{"t":40,"value":-246.26},{"t":60,"value":-148.43},{"t":100,"value":0}],
          opacities: []
        }
      },
      {
        size: { x: 8, y: 11 },
        scale: { x: 100, y: 100 },
        anchor: { x: 4, y: 0 },
        tracks: {
          positions: [{"t":0,"value":{"x":10.07,"y":-9.5}},{"t":20,"value":{"x":0.07,"y":-12.48}},{"t":40,"value":{"x":0.07,"y":-12.48}},{"t":60,"value":{"x":19.7,"y":-19.11}},{"t":80,"value":{"x":16.09,"y":-8.05}},{"t":100,"value":{"x":10.07,"y":-9.5}}],
          rotations: [{"t":0,"value":0},{"t":20,"value":-198.01},{"t":40,"value":-198.01},{"t":60,"value":-114.13},{"t":100,"value":0}],
          opacities: []
        }
      },
    ],
  },
  "125": {
    duration: 109,
    body: {
      size: { x: 40, y: 40 },
      scale: { x: 100, y: 100 },
      anchor: { x: 20, y: 37 },
      tracks: {
        positions: [{"t":0,"value":{"x":0,"y":0}}],
        rotations: [{"t":0,"value":0},{"t":31,"value":-15.7},{"t":49,"value":-15.7},{"t":69,"value":9.6},{"t":85,"value":9.6},{"t":108,"value":0}],
        opacities: []
      }
    },
    weapons: [
      {
        size: { x: 360, y: 200 },
        scale: { x: 9, y: 9 },
        anchor: { x: 89.040281, y: 64.145927 },
        tracks: {
          positions: [{"t":0,"value":{"x":-5.67,"y":-5.94}},{"t":31,"value":{"x":-7.67,"y":-3.94}},{"t":49,"value":{"x":-7.67,"y":-3.94}},{"t":69,"value":{"x":-5.67,"y":-5.94}}],
          rotations: [{"t":0,"value":0},{"t":31,"value":-202.37},{"t":49,"value":-202.37},{"t":69,"value":11.65},{"t":85,"value":11.65},{"t":108,"value":0}],
          opacities: []
        }
      },
    ],
  },
};
